ALTER TABLE "comments" ADD COLUMN "clan_id" uuid;--> statement-breakpoint
ALTER TABLE "reactions" ADD COLUMN "clan_id" uuid;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_clan_id_clans_id_fk" FOREIGN KEY ("clan_id") REFERENCES "public"."clans"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reactions" ADD CONSTRAINT "reactions_clan_id_clans_id_fk" FOREIGN KEY ("clan_id") REFERENCES "public"."clans"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- MANUAL, NOT GENERATED BY drizzle-kit: backfill clan_id for existing rows so the follow-up
-- migration can safely set NOT NULL. Preference order mirrors getClanFeed's own visibility rule
-- (checkIns.createdAt >= clanMemberships.joinedAt): pick the membership joined at-or-before the
-- row's created_at, most recent such membership first; fall back to the user's earliest
-- membership overall if none predates the row.
UPDATE "reactions" AS r
SET "clan_id" = ranked.clan_id
FROM LATERAL (
  SELECT cm.clan_id
  FROM "clan_memberships" cm
  WHERE cm.user_id = r.user_id
    AND cm.joined_at <= r.created_at
  ORDER BY cm.joined_at DESC
  LIMIT 1
) AS ranked
WHERE r.clan_id IS NULL;--> statement-breakpoint
UPDATE "reactions" AS r
SET "clan_id" = ranked.clan_id
FROM LATERAL (
  SELECT cm.clan_id
  FROM "clan_memberships" cm
  WHERE cm.user_id = r.user_id
  ORDER BY cm.joined_at ASC
  LIMIT 1
) AS ranked
WHERE r.clan_id IS NULL;--> statement-breakpoint
UPDATE "comments" AS c
SET "clan_id" = ranked.clan_id
FROM LATERAL (
  SELECT cm.clan_id
  FROM "clan_memberships" cm
  WHERE cm.user_id = c.user_id
    AND cm.joined_at <= c.created_at
  ORDER BY cm.joined_at DESC
  LIMIT 1
) AS ranked
WHERE c.clan_id IS NULL;--> statement-breakpoint
UPDATE "comments" AS c
SET "clan_id" = ranked.clan_id
FROM LATERAL (
  SELECT cm.clan_id
  FROM "clan_memberships" cm
  WHERE cm.user_id = c.user_id
  ORDER BY cm.joined_at ASC
  LIMIT 1
) AS ranked
WHERE c.clan_id IS NULL;